# syntax=docker/dockerfile:1
FROM --platform=linux/amd64  python:3.9-slim-buster 

# Install necessary dependencies
# Install required dependencies and software
RUN  apt-get update \
  && apt-get install -y wget \
  && apt-get install -y unzip \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get update && apt-get install -y gnupg2\
  && apt-get update && apt-get install -y curl unzip jq

# Install Google Chrome
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt-get -yqq update && \
    apt-get -yqq install google-chrome-stable && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /matching

# Copy and install Python dependencies
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Copy the application files
COPY . /matching/

# Command to run the application
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5001"]